
App.STATE_IDENTIFIERS = [
	["NC", "North Carolina"],
	["AL", "Alabama"],
	["MS", "Mississippi"],
	["AR", "Arkansas"],
	["TN", "Tennessee"],
	["SC", "South Carolina"],
	["ME", "Maine"],
	["MI", "Michigan"],
	["OR", "Oregon"],
	["KY", "Kentucky"],
	["IN", "Indiana"],
	["AK", "Alaska"],
	["PA", "Pennsylvania"],
	["WI", "Wisconsin"],
	["OH", "Ohio"],
	["WA", "Washington"],
	["RI", "Rhode Island"],
	["GA", "Georgia"],
	["ID", "Idaho"],
	["WV", "West Virginia"],
	["VA", "Virginia"],
	["OK", "Oklahoma"],
	["KS", "Kansas"],
	["NM", "New Mexico"],
	["MO", "Missouri"],
	["NH", "New Hampshire"],
	["VT", "Vermont"],
	["MA", "Massachusetts"],
	["IL", "Illinois"],
	["TX", "Texas"],
	["MN", "Minnesota"],
	["CT", "Connecticut"],
	["MT", "Montana"],
	["IA", "Iowa"],
	["SD", "South Dakota"],
	["LA", "Louisiana"],
	["NJ", "New Jersey"],
	["AZ", "Arizona"],
	["WY", "Wyoming"],
	["NY", "New York"],
	["UT", "Utah"],
	["CO", "Colorado"],
	["CA", "California"],
	["NE", "Nebraska"],
	["ND", "North Dakota"],
	["DE", "Delaware"],
	["MD", "Maryland"],
	["FL", "Florida"],
	["NV", "Nevada"],
	["HI", "Hawaii"],
	["DC", "District of Columbia", "D.C."]
];
